spring:
    application:
        name: marp

    profiles:
        active: test  

    datasource:
        url: jdbc:postgresql://localhost:5432/so_ti_estagios  
        username: postgres
        password: 6337311
        driverClassName: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: create
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect 